-- Typed models for the DietlyapiIntegration SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
-- params (op.<name>.points[].args.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class Barcode
---@field barcode? string
---@field brand? string
---@field calories_kcal? number
---@field carbs_g? number
---@field category? string
---@field cholesterol_mg? number
---@field confidence? number
---@field fat_g? number
---@field fiber_g? number
---@field id? number
---@field image_thumb_url? string
---@field image_url? string
---@field name? string
---@field potassium_mg? number
---@field protein_g? number
---@field saturated_fat_g? number
---@field serving_desc? string
---@field serving_size_g? number
---@field sodium_mg? number
---@field source? string
---@field static_url? string
---@field sugar_g? number

---@class BarcodeLoadMatch
---@field id string

---@class Food
---@field barcode? string
---@field brand? string
---@field calories_kcal? number
---@field carbs_g? number
---@field category? string
---@field cholesterol_mg? number
---@field confidence? number
---@field count? number
---@field fat_g? number
---@field fiber_g? number
---@field id? number
---@field image_thumb_url? string
---@field image_url? string
---@field name? string
---@field potassium_mg? number
---@field protein_g? number
---@field saturated_fat_g? number
---@field serving_desc? string
---@field serving_size_g? number
---@field sodium_mg? number
---@field source? string
---@field static_url? string
---@field sugar_g? number

---@class FoodLoadMatch
---@field id number

---@class FoodListMatch
---@field barcode? string
---@field brand? string
---@field calories_kcal? number
---@field carbs_g? number
---@field category? string
---@field cholesterol_mg? number
---@field confidence? number
---@field count? number
---@field fat_g? number
---@field fiber_g? number
---@field id? number
---@field image_thumb_url? string
---@field image_url? string
---@field name? string
---@field potassium_mg? number
---@field protein_g? number
---@field saturated_fat_g? number
---@field serving_desc? string
---@field serving_size_g? number
---@field sodium_mg? number
---@field source? string
---@field static_url? string
---@field sugar_g? number

---@class Meta
---@field foods_in_db? number
---@field status? string

---@class MetaLoadMatch
---@field foods_in_db? number
---@field status? string

---@class Popular
---@field barcode? string
---@field brand? string
---@field calories_kcal? number
---@field carbs_g? number
---@field category? string
---@field cholesterol_mg? number
---@field confidence? number
---@field fat_g? number
---@field fiber_g? number
---@field id? number
---@field image_thumb_url? string
---@field image_url? string
---@field name? string
---@field potassium_mg? number
---@field protein_g? number
---@field saturated_fat_g? number
---@field serving_desc? string
---@field serving_size_g? number
---@field sodium_mg? number
---@field source? string
---@field static_url? string
---@field sugar_g? number

---@class PopularListMatch
---@field barcode? string
---@field brand? string
---@field calories_kcal? number
---@field carbs_g? number
---@field category? string
---@field cholesterol_mg? number
---@field confidence? number
---@field fat_g? number
---@field fiber_g? number
---@field id? number
---@field image_thumb_url? string
---@field image_url? string
---@field name? string
---@field potassium_mg? number
---@field protein_g? number
---@field saturated_fat_g? number
---@field serving_desc? string
---@field serving_size_g? number
---@field sodium_mg? number
---@field source? string
---@field static_url? string
---@field sugar_g? number

---@class Search
---@field barcode? string
---@field brand? string
---@field calories_kcal? number
---@field carbs_g? number
---@field category? string
---@field cholesterol_mg? number
---@field confidence? number
---@field fat_g? number
---@field fiber_g? number
---@field id? number
---@field image_thumb_url? string
---@field image_url? string
---@field name? string
---@field potassium_mg? number
---@field protein_g? number
---@field saturated_fat_g? number
---@field serving_desc? string
---@field serving_size_g? number
---@field sodium_mg? number
---@field source? string
---@field static_url? string
---@field sugar_g? number

---@class SearchListMatch
---@field barcode? string
---@field brand? string
---@field calories_kcal? number
---@field carbs_g? number
---@field category? string
---@field cholesterol_mg? number
---@field confidence? number
---@field fat_g? number
---@field fiber_g? number
---@field id? number
---@field image_thumb_url? string
---@field image_url? string
---@field name? string
---@field potassium_mg? number
---@field protein_g? number
---@field saturated_fat_g? number
---@field serving_desc? string
---@field serving_size_g? number
---@field sodium_mg? number
---@field source? string
---@field static_url? string
---@field sugar_g? number

local M = {}

return M
